### ISSUE TITLE
svtplay.se, teckentolkat nedladdat när webstream inte är teckentolkat ...

### ISSUE THREAD

**Issue by SweDennis** [spaam/svtplay-dl#1608]
Using:

```
dennis@gentoo ~ $ svtplay-dl --version
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.72', 'svtplay-dl')
svtplay-dl 4.72
dennis@gentoo ~ $ python --version
Python 3.11.8
dennis@gentoo ~ $ uname -a
Linux gentoo 6.8.6-gentoo #2 SMP PREEMPT_DYNAMIC Sat Apr 13 21:09:34 CEST 2024 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ 
```
Streaming: https://www.svtplay.se/video/eoG2G4G/mastarnas-mastare/avsnitt-10
plays as normal.

svtplay-dl https://www.svtplay.se/video/eoG2G4G/mastarnas-mastare/avsnitt-10
downloads a file which is sign-interpreted,

Either works, but it's clearly not the same file being played.

Regards,
/Dennis

**Comment by spaam** [comment]
yeah it seems to be an issue with the dash parser 🤔

**Comment by SweDennis** [comment]
Won't close the case, but the issue is solved in master as of svtplay-dl 4.72+3.gd814ba7, for those interested ...

/Dennis

**Comment by spaam** [comment]
4.73 got ze fix :D

**Comment by SweDennis** [comment]
Problem is back.

Using:

```
dennis@gentoo ~ $ svtplay-dl --version
/usr/bin/svtplay-dl:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').run_script('svtplay-dl==4.73+1.g587754b', 'svtplay-dl')
svtplay-dl 4.73+1.g587754b
dennis@gentoo ~ $ python --version
Python 3.11.9
dennis@gentoo ~ $ uname -a
Linux gentoo 6.8.9-gentoo #2 SMP PREEMPT_DYNAMIC Sat May  4 21:07:56 CEST 2024 x86_64 Intel(R) Core(TM) i3-3240 CPU @ 3.40GHz GenuineIntel GNU/Linux
dennis@gentoo ~ $ 
```

Streaming : https://www.svtplay.se/video/KA3LyJ3/detektiverna/arantxa-tar-pulsen-pa-detektiverna?id=KA3LyJ3
Plays as normal

Downloading: svtplay-dl https://www.svtplay.se/video/KA3LyJ3/detektiverna/arantxa-tar-pulsen-pa-detektiverna?id=KA3LyJ3  
Downloads "syntolkat"

Regards,
/Dennis

**Comment by spaam** [comment]
4.79 should have a fix for this in case you missed my message .)

**Comment by SweDennis** [comment]
Haven't seen any message, but 4.79 does indeed download the correct file of detektiverna ... Should the issue return, you'd be the first to know ...
